[[tests]]
name = "to_upper_1"
input = ["./to_upper", "foobar"]
expected = """
C: FOOBAR
Asm: FOOBAR
"""
rubric = 10

[[tests]]
name = "to_upper_2"
input = ["./to_upper", "FooBar1{}"]
expected = """
C: FOOBAR1{}
Asm: FOOBAR1{}
"""
rubric = 10

[[tests]]
name = "max3_1"
input = ["./max3", "1", "2", "3"]
expected = """
C: 3
Asm: 3
"""
rubric = 10

[[tests]]
name = "max3_2"
input = ["./max3", "3", "2", "1"]
expected = """
C: 3
Asm: 3
"""
rubric = 10

[[tests]]
name = "fmi_1"
input = ["./find_max_index", "3", "2", "1"]
expected = """
C: 0
Asm: 0
"""
rubric = 10

[[tests]]
name = "fmi_2"
input = ["./find_max_index", "1", "2", "3"]
expected = """
C: 2
Asm: 2
"""
rubric = 10

[[tests]]
name = "sort_1"
input = ["./sort", "1", "2", "3"]
expected = """
C: 3 2 1
Asm: 3 2 1
"""
rubric = 10

[[tests]]
name = "sort_2"
input = ["./sort", "2", "7", "4", "1"]
expected = """
C: 7 4 2 1
Asm: 7 4 2 1
"""
rubric = 10

