[project]
build = "none"
strip_output = """
Use default settings!
"""

[[tests]]
name = "part1"
input = ["java", "-cp", "$digital", "CLI", "test", "$project_part1.dig", "-tests", "$project_tests/part1-test.dig"]
expected = """
part1-test: passed
"""
rubric = 80

[[tests]]
name = "part2"
input = ["java", "-cp", "$digital", "CLI", "test", "$project_part2.dig", "-tests", "$project_tests/part2-test.dig"]
expected = """
part2-test: passed
"""
rubric = 20

